site_name: Thinking Garden

theme:
  name: material
  language: zh
  features:
    - content.code.copy
    - navigation.tabs
  custom_dir: overrides
  font:
    text: Noto Sans SC
    code: Fira Code

# 代码块高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

# plugins:
#   - search:
#     separator: '[\s\u200b\-]'
#       # lang:
#       #   - en
#       #   - zh


plugins:
  - search:
      separator: '[\s\u200b\-]'
  - sys_time_plugin

extra_css:
  - stylesheets/extra.css
