site_name: Thinking Garden

theme:
  name: material
  language: zh
  features:
    - content.code.copy
  font:
    text: Noto Sans SC
    # code: Fira Code

# 代码块高亮
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
  - search:
      lang:
        - en
        - zh